# Generated by Django 5.0.14 on 2025-12-18 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommercePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform_type', models.CharField(choices=[('homabay_souq', 'HomaBay Souq'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('magento', 'Magento'), ('custom', 'Custom Platform')], max_length=20)),
                ('base_url', models.URLField()),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_interval', models.IntegerField(default=5, help_text='Sync interval in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'E-commerce Platform',
                'verbose_name_plural': 'E-commerce Platforms',
            },
        ),
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration Configuration',
                'verbose_name_plural': 'Integration Configurations',
            },
        ),
        migrations.CreateModel(
            name='OrderSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('webhook', 'Webhook'), ('manual', 'Manual'), ('scheduled', 'Scheduled'), ('api_pull', 'API Pull')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], max_length=20)),
                ('orders_synced', models.IntegerField(default=0)),
                ('orders_failed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='delivery.ecommerceplatform')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderSyncRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('status_filter', 'Status Filter'), ('payment_filter', 'Payment Filter'), ('date_filter', 'Date Filter'), ('value_filter', 'Order Value Filter'), ('customer_filter', 'Customer Filter')], max_length=20)),
                ('condition', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_rules', to='delivery.ecommerceplatform')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='OrderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_order_id', models.CharField(db_index=True, max_length=255)),
                ('platform_order_number', models.CharField(db_index=True, max_length=255)),
                ('raw_order_data', models.JSONField(default=dict)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('delivery_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_mapping', to='delivery.deliveryrequest')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_mappings', to='delivery.ecommerceplatform')),
            ],
            options={
                'indexes': [models.Index(fields=['platform_order_id', 'platform_order_number'], name='delivery_or_platfor_8eac09_idx')],
                'unique_together': {('platform', 'platform_order_id')},
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_cancelled', 'Order Cancelled'), ('order_paid', 'Order Paid'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_refunded', 'Order Refunded'), ('payment_failed', 'Payment Failed')], max_length=50)),
                ('event_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=255)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='delivery.ecommerceplatform')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_id', 'platform'], name='delivery_we_event_i_7b48a1_idx'), models.Index(fields=['created_at'], name='delivery_we_created_d15c52_idx')],
            },
        ),
    ]
