# Generated by Codex on 2026-03-13
from django.db import migrations, models


ROUTE_FEES = [
    ('homabay', 'mbita', 200),
    ('homabay', 'oyugis', 200),
    ('homabay', 'kendu', 200),
    ('homabay', 'suba', 300),
    ('homabay', 'rodi', 150),
    ('homabay', 'ndhiwa', 200),
    ('mbita', 'rodi', 300),
    ('rodi', 'suba', 400),
    ('rodi', 'kendu', 200),
    ('rodi', 'oyugis', 200),
    ('oyugis', 'mbita', 300),
    ('oyugis', 'suba', 350),
    ('kendu', 'suba', 350),
    ('mbita', 'suba', 200),
]


def seed_route_rates(apps, schema_editor):
    DeliveryRouteRate = apps.get_model('delivery', 'DeliveryRouteRate')
    for origin, destination, fee in ROUTE_FEES:
        DeliveryRouteRate.objects.get_or_create(
            origin=origin,
            destination=destination,
            defaults={'base_fee': fee}
        )
        DeliveryRouteRate.objects.get_or_create(
            origin=destination,
            destination=origin,
            defaults={'base_fee': fee}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_delivery_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRouteRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('homabay', 'Homabay'), ('mbita', 'Mbita'), ('oyugis', 'Oyugis'), ('kendu', 'Kendu Bay'), ('suba', 'Suba'), ('rodi', 'Rodi Kopany')], max_length=30)),
                ('destination', models.CharField(choices=[('homabay', 'Homabay'), ('mbita', 'Mbita'), ('oyugis', 'Oyugis'), ('kendu', 'Kendu Bay'), ('suba', 'Suba'), ('rodi', 'Rodi Kopany')], max_length=30)),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['origin', 'destination'],
                'unique_together': {('origin', 'destination')},
            },
        ),
        migrations.RunPython(seed_route_rates, migrations.RunPython.noop),
    ]
