# Generated by Codex on 2026-03-13
from django.db import migrations


def seed_ndhiwa_rate(apps, schema_editor):
    DeliveryRouteRate = apps.get_model('delivery', 'DeliveryRouteRate')
    # Ensure homabay <-> ndhiwa exists
    DeliveryRouteRate.objects.get_or_create(
        origin='homabay',
        destination='ndhiwa',
        defaults={'base_fee': 200}
    )
    DeliveryRouteRate.objects.get_or_create(
        origin='ndhiwa',
        destination='homabay',
        defaults={'base_fee': 200}
    )


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_delivery_route_rates'),
    ]

    operations = [
        migrations.RunPython(seed_ndhiwa_rate, migrations.RunPython.noop),
    ]
