# Generated by Django 6.0.3 on 2026-03-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_deliveryprofile_id_alter_deliveryrouterate_id'),
        ('delivery', '0009_ndhiwa_route_rate'),
    ]

    operations = [
    ]
