# Generated by Django 6.0.3 on 2026-03-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_add_missing_route_rates_cap_350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrouterate',
            name='destination',
            field=models.CharField(choices=[('homabay', 'Homabay'), ('mbita', 'Mbita'), ('oyugis', 'Oyugis'), ('kendu', 'Kendu Bay'), ('suba', 'Suba'), ('rodi', 'Rodi Kopany'), ('ndhiwa', 'Ndhiwa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='deliveryrouterate',
            name='origin',
            field=models.CharField(choices=[('homabay', 'Homabay'), ('mbita', 'Mbita'), ('oyugis', 'Oyugis'), ('kendu', 'Kendu Bay'), ('suba', 'Suba'), ('rodi', 'Rodi Kopany'), ('ndhiwa', 'Ndhiwa')], max_length=30),
        ),
    ]
