# Generated by Codex on 2026-03-15
from django.db import migrations, models
from django.db.models.functions import Lower


def dedupe_emails(apps, schema_editor):
    User = apps.get_model('users', 'User')

    # Normalize to lowercase to align with the case-insensitive constraint.
    for user in User.objects.exclude(email__isnull=True).exclude(email=''):
        normalized = user.email.strip().lower()
        if user.email != normalized:
            user.email = normalized
            user.save(update_fields=['email'])

    # Keep the earliest account, rename/deactivate duplicates.
    seen = {}
    for user in User.objects.exclude(email__isnull=True).exclude(email='').order_by('date_joined', 'id'):
        key = user.email.lower()
        if key in seen:
            suffix = f"dup-{user.id}-"
            base = key
            max_len = 254
            if len(suffix) + len(base) > max_len:
                base = base[: max_len - len(suffix)]
            user.email = f"{suffix}{base}"
            user.is_active = False
            user.email_verified = False
            user.save(update_fields=['email', 'is_active', 'email_verified'])
        else:
            seen[key] = user.id


def restore_noop(apps, schema_editor):
    # No-op: we can't reliably restore previous duplicate emails.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0019_usersettings'),
    ]

    operations = [
        migrations.RunPython(dedupe_emails, restore_noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(
                Lower('email'),
                name='uniq_users_email_ci',
                condition=~models.Q(email__isnull=True) & ~models.Q(email='')
            ),
        ),
    ]
