# Generated by Django 5.0.14 on 2025-12-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_create_favorited_m2m_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingFavoritedBy',
        ),
    ]
