# Generated by Django 5.0.14 on 2026-01-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_reviewphoto_reviewtype_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='favorited_by',
        ),
    ]
