# Generated by Django 5.0.14 on 2026-01-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_reviewphoto_reviewtype_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Skip database operations entirely - field was never actually created in DB
            database_operations=[],
            # Update Django's state to remove the field
            state_operations=[
                migrations.RemoveField(
                    model_name='listing',
                    name='favorited_by',
                ),
            ]
        ),
    ]
