# Generated by Django 5.0.14 on 2026-01-12 19:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_auto_20260112_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, folder='baysoko/listings/', null=True),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, folder='baysoko/listings/gallery/', null=True),
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, folder='baysoko/reviews/', null=True),
        ),
    ]
