# Generated by Django 5.0.14 on 2026-01-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_alter_image_fields_cloudinary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/gallery/'),
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_photos/'),
        ),
    ]
