# Generated by Codex on 2026-03-13
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_newslettersubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='ready_for_release',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrow',
            name='approved_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='escrow_approvals',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='escrow',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
