# Generated by Codex on 2026-03-13
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_escrow_approval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_place_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
