# Generated by Codex on 2026-03-13
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0041_order_shipping_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
