# Generated by Django 6.0.6 on 2026-06-24 13:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0045_listingvideocomment_listingvideolike'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=5),
        ),
    ]
