# Generated by Django 5.0.14 on 2026-01-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0010_inventoryaudit_productvariant_stockmovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured stores get premium placement'),
        ),
    ]
