# Generated by Django 5.0.14 on 2026-01-19 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0011_store_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_number',
            field=models.PositiveIntegerField(default=0, help_text='Which trial number this is for the user'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('canceled', 'Canceled'), ('converted', 'Converted to Paid')], default='active', max_length=20)),
                ('days_used', models.PositiveIntegerField(default=0)),
                ('features_accessed', models.JSONField(blank=True, default=list)),
                ('conversion_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='storefront.store')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_records', to='storefront.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Trial',
                'verbose_name_plural': 'User Trials',
                'ordering': ['-started_at'],
                'unique_together': {('user', 'trial_number')},
            },
        ),
    ]
