# Generated by Django 5.0.14 on 2026-01-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0013_batchjob_bulkoperationlog_exportjob_importtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
