# Generated by Django 5.0.14 on 2026-01-28 09:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0014_store_total_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_orders', models.IntegerField(default=0)),
                ('active_stores', models.IntegerField(default=0)),
                ('active_listings', models.IntegerField(default=0)),
                ('revenue_trend', models.FloatField(default=0)),
                ('orders_trend', models.FloatField(default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('seller', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StoreAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('orders_count', models.IntegerField(default=0)),
                ('active_listings', models.IntegerField(default=0)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('views', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='storefront.store')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('store', 'date')},
            },
        ),
    ]
