# Generated by Django 5.0.14 on 2026-02-07 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0018_store_payout_phone_store_payout_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_verifications', to='storefront.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
