# Generated by Codex on 2026-03-13
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0020_alter_store_cover_image_alter_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='mpesa_conversation_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='mpesa_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='mpesa_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='mpesa_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='mpesa_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
